### ISSUE TITLE
Unable to enable plugin in LO 4.4.6.3

### ISSUE THREAD

**Issue by Pantek59** [Mendeley/openoffice-plugin#19]
Hi there

I don't know whether the problem is really with the Mendeley plug-in or rather with Libre Office itself, but I have to start reporting it somewhere. :)

When I started Mendeley after a few months not using it, it came up with an error message concerning the OO plugin and afterwards the plug-in was disabled in LO. When trying to re-enable it, the following error message appears:
*"ImplementationRegistration::registerImplementation() - The service com.sun.star.loader.Python cannot be instantiated"*.

Ubuntu version: 14.04
Mendeley version: 1.15.1
Libre Office version: 4.4.6.3

Removing and re-installing the plug-in didn't bring any improvement, btw.
Thanks for your time,
 Jan

**Comment by cablegunmaster** [comment]
Try: 
    sudo apt-get install libreoffice-script-provider-python  
This will install a dependency python-uno which will resolve your issue.

**Comment by Pantek59** [comment]
This package and a bit of dependency hunting did the job. Thanks for the hint!

**Comment by karl616** [comment]
Under fedora the package was libreoffice-pyuno
