### ISSUE TITLE
Export as MS Word Compatible not working anymore

### ISSUE THREAD

**Issue by trespanes** [Mendeley/openoffice-plugin#35]
I try to export a Document containing Citations to a wordfile to be able to colaborate with other researchers. When doing so via the plugin, the citations are converted to plain text. No further modification is possible anymore. I checked on two different setups:

- (1) Ubuntu 16.04, Libreoffice Version: 5.4.2.2 installed from libreoffice PPA with Mendeley Desktop 1.17.10
- (2) Ubuntu 16.04, Libreoffice Version: 5.1.6.2 installed from Ubuntu Official PPA with Mendeley Deskto 1.17.11

Here is a step-by-step procedure to reproduce:
- insert a citation with the mendely plugin
- save as (odf).
- export MS word compatible via the mendeley plugin (saves it as .doc)
- open the .doc file in libreoffice again and try to modify the citation --> does not work because it is converted to plain text.

Also the plugin saves the document with the .doc extension which is not supported by default from MS Office anymore. Users are always asked to convert to docx. which will probably introduce further problems. What can I do to solve this?

**Comment by trespanes** [comment]
i had to push the refresh button to make citations appear again. was not aware of that. sorry. Export to docx. would be awesome!

**Comment by cpina** [comment]
Thanks trespanes for opening the detailed ticket and commenting it.

Just a quick reference for the future for anyone else:
When using the "Export MS Word Compatible" from LibreOffice it changes the citations from fields (by default with a grey shade) to bookmarks.

The bookmarks don't have any grey field and this is confusing. When using this document on Microsoft Word the Word plugin should change from bookmarks back to fields with the usual grey colour.
